### ISSUE TITLE
[Request] Add Tag to Tag method to TagProvider

### ISSUE THREAD

**Issue by remplerus** [NovaMachina-Mods/NovaCore#2]
### Is there an existing suggestion for this?

- [X] I have searched the existing suggestions

### Feature Description

Adding existing tags to our tags can't be done as there's no method for it.

### Provided Benefit

We can use tags to make our mods more configurable.

**Comment by NovaMachina** [comment]
Should be possible via: https://github.com/NovaMachina-Mods/NovaCore/blob/aa2827fa6e8806ab23fad9917a42112898bb1a92/src/main/java/novamachina/novacore/data/tags/TagBuilder.java#L26-L33
